sonar.projectKey=aatmaja24-git_Student_Cloud_Toolkit_1
sonar.organization=aatmaja24-git
sonar.projectName=Student_Cloud_Toolkit_1
sonar.sources=backend,frontend
sonar.exclusions=**/node_modules/**,**/.git/**,**/*.min.js,**/venv/**,**/__pycache__/**